### PR TITLE
Adding unittests

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by sils1297** [comment]
coverage submission not working?

**Comment by AbdealiJK** [comment]
I haven't added the coverage submission part yet - was not sure how to do it with karma. Am doing it now

**Comment by sils1297** [comment]
@AbdealiJK can you resolve conflicts?

**Comment by sils1297** [comment]
@AbdealiJK can you finish this up so we can review and merge it?

**Comment by AbdealiJK** [comment]
Wow, I forgot about this ...

**Comment by AbdealiJK** [comment]
Um, I seem to need some help here.

1. gitmate keeps creating the label "pending review" when we are using "process/pending review" - I don't know why it does that

2. Travis doesnt build it :/ I tried force pushing 3 times and it never began a build for this PR. It seems like travis has no idea that this branch has been updated: https://travis-ci.org/coala-analyzer/coala-html/branches

**Comment by sils1297** [comment]
> gitmate keeps creating the label "pending review" when we are using "process/pending review" - I don't know why it does that

I changed it in the gitmate configuration, should work now

**Comment by sils1297** [comment]
> Travis doesnt build it :/ 

maybe make a new branch and PR? And email them...

**Pull request closed without merging**
