### PR TITLE
Readme

### PR DESCRIPTION
**Pull request by Ifeanyijasper**
**For short term contributors:** we understand that getting your commits well
defined like we require is a hard task and takes some learning. If you
look to help without wanting to contribute long term there's no need
for you to learn this. Just drop us a message and we'll take care of brushing
up your stuff for merge!

### Checklist

- [x] I read the [commit guidelines](http://coala.io/commit) and I've followed
      them.
- [x] I ran coala over my code locally. (*All commits have to pass
      individually.* It is not sufficient to have "fixup commits" on your PR,
      our bot will still report the issues for the previous commit.) You will
      likely receive a lot of bot comments and build failures if coala does not
      pass on every single commit!

After you submit your pull request, **DO NOT click the 'Update Branch' button.**
When asked for a rebase, consult [coala.io/rebase](https://coala.io/rebase)
instead.

Please consider helping us by reviewing other peoples pull requests as well:

- pick up any PR at <https://coala.io/review>
- review it (check <https://coala.io/reviewing> for more info)
- if you are sure that it needs work, use `cobot mark wip <URL>` to get it out
  of the review queue.

The more you review, the more your score will grow at coala.io and we will
review your PRs faster!

### CODE REVIEW

**Review by Gromy1211 — COMMENTED** [review]
Hi, I think you need to squash your commits. You may refer https://api.coala.io/en/latest/Developers/Git_Basics.html#squashing-your-commits   :)

**Review by chay2199 — COMMENTED** [review]
Please change README.md --> README.rst in your commit message or maybe you should not even mention the file again as it is already present in the commit head.

**Review by KVGarg — APPROVED** [review]

**Review by AkshJain99 — APPROVED** [review]
this pr is fine but change the pr description as per coala guidelines so that mainatiners can approve this
LGTM

**Review by gr455 — APPROVED** [review]

**Comment by KVGarg** [comment]
@Ifeanyijasper May I know the reason of closing this PR? This practice should not be followed of closing the PRs un-necessarily. It should be avoided by a contributor.

**Pull request closed without merging**
