### PR TITLE
README.rst: Add badges and demo

### PR DESCRIPTION
**Pull request by tushar-rishav**
Add badges and demo at http://coala-analyzer.github.io/coala-html/#/
Closes https://github.com/coala-analyzer/coala-html/issues/69

### CODE REVIEW

**Comment by Uran198** [comment]
ack 4eba9cf

**Comment by tushar-rishav** [comment]
@Uran198 Ah. I just pinged you at Skype regarding this PR. :D

**Comment by tushar-rishav** [comment]
@rultor merge

**Comment by tushar-rishav** [comment]
reack 4eba9cf

**Comment by tushar-rishav** [comment]
@rultor merge kar lo bhai

**Pull request merged**
