### PR TITLE
main.html: Display file paths in Results

### PR DESCRIPTION
**Pull request by tushar-rishav**
Fixes https://github.com/coala-analyzer/coala-html/issues/29 and https://github.com/coala-analyzer/coala-html/issues/26

### CODE REVIEW

**Comment by AbdealiJK** [comment]
Can yuo remove the commit with find ? Then we can merge the other one - I'd rather not merge the search as we have no idea when it breaks and when it doesnt

**Comment by tushar-rishav** [comment]
@AbdealiJK Done

**Comment by tushar-rishav** [comment]
Should have labeled it as a newcomer bug. Anyway next time :P

**Comment by AbdealiJK** [comment]
ack 6c143c5

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
