### PR TITLE
Add more things

### PR DESCRIPTION
**Pull request by AbdealiJK**

### CODE REVIEW

**Comment by tushar-rishav** [comment]
@AbdealiJK  IMO we should also display file paths along with errors and affected lines in Results tab. Having that will help users to narrow down the search for errors. What do you think?

**Comment by AbdealiJK** [comment]
@tushar-rishav I agree ! (I did not realize we aren't doing this)
Could you file a bug for that ?

**Comment by tushar-rishav** [comment]
ack :dart: 
3a98bfe files.html: Add links to table rows
338647b main.css: Move prettyprint linenums to index
3560047 files: Add demo of Files tab using simple project
8e9b648 test_projects/simple: Add directory and files.json
9afdb10 app: Move all directives to own file
49c6ce3 index: Use bsNavActive for navbar active element
e2609de main, logs: Use rootScope variables
f98c3c0 app: Add rootScope variables
5969879 logs: Add functionality
f26275f app: Add new controller+view Logs
7b53673 index.html: Rename Home as Results in navbar
dfc906f main.css: Cleanup code
a50874f index.html: Use Lato as font everywhere
1bb2da6 main.css: Remove monotype font
895b297 main.css: Use Lato as the sans-serif font
cdb6e8d gitignore: Remove folders used in bower_components
46c6fae jshintrc: Add global variable - prettyPrintOne

**Comment by AbdealiJK** [comment]
@rultor merge

**Pull request merged**
